name: CI Client Features

on: push

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt update && sudo apt install build-essential libgtest-dev cmake gcc valgrind
      - name: build
      - uses: actions/checkout@v2
        run: make build
  